### ISSUE TITLE
question(auth): Using AngularFire instead of FirebaseAuth

### ISSUE THREAD

**Issue by andlcool** [r-park/todo-angular2-firebase#107]
Read the code. Impressive. Have a few questions hope you can answer and I can learn from you.

1. Why in your code auth-service.ts you're using FirebaseAuth instead of AngularFire?
2. Why use public here? Why not private like `private af: AngularFire`?
3. Why use auth$ to represent it? Why not just use auth...

```
  constructor(public auth$: FirebaseAuth, private af: AngularFire) {
   auth$.subscribe((state: FirebaseAuthState) => {
      this.authState = state;
    });
   /*af.auth.subscribe((state: FirebaseAuthState) => {
      this.authState= state;
    })*/
  }
```

**Comment by r-park** [comment]
1. Just personal preference – since the service only needs FirebaseAuth, no need to inject AngularFire proper.

2. I think `public` is a hold-over from previous iterations that may have exposed `auth$` for components to subscribe to.

3. The `$` suffix is a oft-used convention for identifying observable streams.

**Comment by choopage** [comment]
Nice. I just learned something from you reading this answer.

**Comment by andlcool** [comment]
Thanks for the quick reply. Learnt something new. 👍
