### ISSUE TITLE
Adding external javascript libraries?

### ISSUE THREAD

**Issue by tanvirshuvo** [r-park/todo-angular2-firebase#126]
How to add external javascript libraries to this project?
For say, If I want to add bootstrap? For any javascript plugin?
Life without javascript plugins is like living in 1730.

**Comment by mhadaily** [comment]
Your question is irrelevant to this repo. You are able to add any kinda library to an Angular2 project as easy as the following steps:
1- Install through NPM 
2- since this project using Webpack, inject your script here! 
3- the worse can be to add your script to the main index.html. 

However, for most of what you need these days, you are able to find an NPM package and easy import to the project. For instance, https://www.npmjs.com/package/bootstrap-sass
