### ISSUE TITLE
Use of ReplaySubject in Task Store

### ISSUE THREAD

**Issue by doovers** [r-park/todo-angular2-firebase#46]
I'm trying to get my head around RxJS and I'm wondering about your use of ReplaySubject in the TaskStore. According to the docs, ReplaySubject "emits to any observer all of the items that were emitted by the source Observable(s), regardless of when the observer subscribes". To me this doesn't make sense as it seems we are only interested in the last item emitted (i.e. the most recent value of the FirebaseSnapshot). Maybe I'm missing something here (angular and rxjs are both very new to me!) but I'd like to hear the reasoning behind your choice of ReplaySubject vs BehaviorSubject here.

**Comment by r-park** [comment]
A [ReplaySubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/replaysubject.md) with a buffer size of 1 `new ReplaySubject(1)` acts like a [BehaviorSubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md). For the purposes of this todo example, either one will work. 

Each time one of the filter links is clicked  (view all, active, completed), a route change occurs causing the `AsyncPipe` to re-subscribe to the `tasks` ReplaySubject. The reason a ReplaySubject (or BehaviorSubject) is used instead of a plain Subject, is to ensure that the `AsyncPipe` always receives the latest list of tasks each time it subscribes.

**Comment by doovers** [comment]
Aha! I didn't see the buffer size parameter. Thanks for the explanation that makes total sense now.
